applications:
    gateway:
        type: nodejs:20
        web:
            commands:
                start: node server.js
            locations:
                /:
                    passthru: true
                /xhttp:
                    passthru: true

routes:
  https://{default}/:
    type: proxy
    to: http://134.122.52.175:80
  http://{default}/:
    type: redirect
    to: https://{default}/
