applications:
  app:
    type: nodejs:20
    web:
      commands:
        start: node server.js
      locations:
        /:
          passthru: true

routes:
  "https://{default}/":
    type: proxy
    to: "http://188.213.28.174:80"
  "http://{default}/":
    type: redirect
    to: "https://{default}/"
